export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  GROCERY_CREATED = 'GROCERY_CREATED',
  GROCERY_UPDATED = 'GROCERY_UPDATED',
  GROCERY_DELETED = 'GROCERY_DELETED',
  INVENTORY_UPDATED = 'INVENTORY_UPDATED',
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_PLACE_FAILED = 'ORDER_PLACE_FAILED',
  LOW_STOCK_ALERT = 'LOW_STOCK_ALERT',
}
